### ISSUE TITLE
NFC error

### ISSUE THREAD

**Issue by number12** [coderkevin/mini-nes#8]
I followed all the instructions and python is installed correctly. The button code does work and the process is running. Anyways I skipped the NFC a couple times because of this error and got a new NFC reader incase, and still same error. Wondering if there is a fix Everything goes smoothly but when I type the command "nfc-poll" it gives the following error 

> pi@retropie:~ $ nfc-poll
nfc-poll uses libnfc 1.7.1
error   libnfc.bus.i2c  Error: wrote only -1 bytes (10 expected).
error   libnfc.driver.pn532_i2c Unable to transmit data. (TX)
pn53x_check_communication: Input / Output Error
error   libnfc.bus.i2c  Error: wrote only -1 bytes (10 expected).
error   libnfc.driver.pn532_i2c Unable to transmit data. (TX)
nfc-poll: ERROR: Unable to open NFC device.

Wondering if I did something wrong? I wired it correctly im sure. Thanks for help.
![img_20170823_171103 1](https://user-images.githubusercontent.com/2688150/29643786-3c6d285a-8826-11e7-92de-11d9deaddad0.jpg)

**Comment by Xerxes3rd** [comment]
@number12 It looks like you might have the DIP switches on the NFC board set to SPI instead of I2C.

**Comment by thepiwizard** [comment]
very last step fails 
also the tail nfc-poll thing fails 

pi@retropie:~ $ sudo systemctl restart nfc_poll

Job for nfc_poll.service failed because the control process exited with error code.
See "systemctl status nfc_poll.service" and "journalctl -xe" for details.
pi@retropie:~ $ systemctl status nfc_poll.service
â— nfc_poll.service - LSB: start and stop nfc_poll server
   Loaded: loaded (/etc/init.d/nfc_poll; generated)
   Active: failed (Result: exit-code) since Fri 2021-09-17 19:33:41 BST; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2371 ExecStart=/etc/init.d/nfc_poll start (code=exited, status=1/FAILURE)

Sep 17 19:33:41 retropie nfc_poll[2371]: Traceback (most recent call last):
Sep 17 19:33:41 retropie nfc_poll[2371]:   File "/var/lib/nfc_poll/nfc_poll_daemon.py", line 64, in <module>
Sep 17 19:33:41 retropie nfc_poll[2371]:     start_daemon( args.pid_file, args.log_file )
Sep 17 19:33:41 retropie nfc_poll[2371]:   File "/var/lib/nfc_poll/nfc_poll_daemon.py", line 54, in start_daemon
Sep 17 19:33:41 retropie nfc_poll[2371]:     sys.exit(1)
Sep 17 19:33:41 retropie nfc_poll[2371]: NameError: global name 'sys' is not defined
Sep 17 19:33:41 retropie nfc_poll[2371]:  failed!
Sep 17 19:33:41 retropie systemd[1]: nfc_poll.service: Control process exited, code=exited, status=1/FAILURE
Sep 17 19:33:41 retropie systemd[1]: nfc_poll.service: Failed with result 'exit-code'.
Sep 17 19:33:41 retropie systemd[1]: Failed to start LSB: start and stop nfc_poll server.
pi@retropie:~ $

**Comment by coderkevin** [comment]
Fixed in 3b26b25633fca2e90fd475dfe22be0519cc7030a
